# Generated by Django 5.0.2 on 2024-03-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.URLField(blank=True)),
                ('player_image', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
            options={
                'verbose_name': 'Selected Player',
                'verbose_name_plural': 'Selected Players',
                'db_table': 'selected_player',
                'ordering': ['-date'],
            },
        ),
    ]
