name: Select Correct Player

jobs:
  update-selected-player:
    runs-on: ubuntu-latest

    steps:
      - name: Print Directory Contents
        run: ls -al

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Management Command
        run: |
          python manage.py update_selected_player
